package com.safari.utils

const val LOGIN = "login"
const val SIGNUP = "signup"
const val HOME = "home"
const val ROOT = "root"
const val CONTENT = "content"
const val AUTHENTICATION = "authentication"
const val ADD = "Add Item to Shop"
const val FOOD = "Food"
const val CLOTHES = "Clothes"
const val DRINKS = "Drinks"
const val SHOPPINGLIST = "shoppingList"
const val ACCOUNT = "account"
const val ADDITEMS = "addItems"
const val USERS = "users"
const val TOSHOP = "toShopItems"
const val IMAGE = "safariImages"
const val UPDATE = "updateItem"
const val SMS = "sms"
const val TARGET = "share_target_route"